version: '3.8'

services:
  omniflow:
    build: .
    container_name: omniflow_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EMAIL_USER=raspberryrecive@gmail.com
      - EMAIL_PASSWORD=eason070725_Sy  # 填入 16 位元 Google 應用程式專用密碼
      - EMAIL_HOST=imap.gmail.com