version: '3.8'

services:
  omniflow:
    build: .
    container_name: omniflow_app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EMAIL_USER=${EMAIL_USER}  
      - EMAIL_PASSWORD=${EMAIL_PASSWORD} 
      - EMAIL_HOST=imap.gmail.com
      - NODE_TLS_REJECT_UNAUTHORIZED=0